title: Ben Wilson - Adventures in SBDM
email: ben@thelocust.org
description: >- # this means to ignore newlines until "baseurl:"
  Adventures in SBDM - My experiences as an Site-Based Decision-Making Council
  Parent Representative for Lincoln Performing Arts Elementary School in Louisville, Kentucky.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://benwilson.org/sbdm"
production_url : https://benwilson.org/sbdm

twitter_username: mynamesiswilson
github_username:  mynamesiswilson

permalink: /:year:month:day-:title:output_ext

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
